# Generated by Django 4.2.6 on 2023-10-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='page',
            field=models.CharField(default='main', max_length=30),
            preserve_default=False,
        ),
    ]
