# Generated by Django 4.2.6 on 2023-10-27 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menu_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='submenu',
            name='submenu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='menu.menu'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submenu',
            name='main_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu', to='menu.menu'),
        ),
    ]
